version: '3.4'

services:

  mongodb:
    image: mongo:latest
    container_name: MongoDB
    ports:
      - 27017:27017
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password123
    volumes:
      - .\MongoDB\data:/data/db

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: SqlServer
    ports:
      - 1433:1433
    environment:
      - TZ=Asia/Shanghai
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    volumes:
      - .\SqlServer\data:/var/opt/mssql/data
      - .\SqlServer\log:/var/opt/mssql/log
      - .\SqlServer\secrets:/var/opt/mssql/secrets